export const products = [
  {
    id: 1,
    name: "Earthen Bottle",
    href: "#",
    price: "₹150",
    description: "A beautiful, handcrafted earthen bottle for your beverages.",
    rating: 4.5,
    features: ["Handmade", "Eco-friendly", "Durable"],
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-01.jpg",
    imageAlt:
      "Tall slender porcelain bottle with natural clay textured body and cork stopper.",
    isTrending: false,
    category: [{ name: "kids" }, { name: "household" }],
    stock: 100,
    brand: "EarthenWare",
    weight: "500g",
    dimensions: { length: "25cm", width: "8cm", height: "8cm" },
    material: "Clay",
    colors: ["Brown", "Beige"],
    size: ["500ml", "750ml"],
    reviews: [
      {
        reviewer: "John Doe",
        rating: 4.5,
        comment: "Great product, very durable and eco-friendly.",
      },
    ],
    salePrice: "180",
    relatedProducts: [2, 3],
    SKU: "EW-BTL-001",
    dateAdded: "2024-01-15",
    manufacturer: "EarthenWare Co.",
    warranty: "1 year",
    shippingDetails: "Free shipping on orders over ₹500",
    returnPolicy: "30-day return policy",
  },
  {
    id: 2,
    name: "Nomad Tumbler",
    href: "#",
    price: "₹200",
    description: "A versatile tumbler for your everyday hydration needs.",
    rating: 4.0,
    features: ["Insulated", "BPA-free", "Dishwasher safe"],
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-02.jpg",
    imageAlt:
      "Olive drab green insulated bottle with flared screw lid and flat top.",
    isTrending: true,
    category: [{ name: "household" }],
    stock: 50,
    brand: "Nomad",
    weight: "300g",
    dimensions: { length: "20cm", width: "7cm", height: "7cm" },
    material: "Stainless Steel",
    colors: ["Green", "Black"],
    size: ["350ml", "500ml"],
    reviews: [
      {
        reviewer: "Jane Smith",
        rating: 4.0,
        comment: "Good quality, keeps my drinks hot for hours.",
      },
    ],
    salePrice: "260",
    relatedProducts: [1, 4],
    SKU: "NMD-TMB-002",
    dateAdded: "2024-02-10",
    manufacturer: "Nomad Co.",
    warranty: "2 years",
    shippingDetails: "Free shipping on orders over ₹500",
    returnPolicy: "30-day return policy",
  },
  {
    id: 3,
    name: "Focus Paper Refill",
    href: "#",
    price: "₹500",
    description: "A refill pack for your productivity-focused notebooks.",
    rating: 4.5,
    features: ["High-quality paper", "Fits most planners", "Eco-friendly"],
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-03.jpg",
    imageAlt:
      "Person using a pen to cross a task off a productivity paper card.",
    isTrending: false,
    category: [{ name: "men" }, { name: "women" }],
    stock: 200,
    brand: "Focus",
    weight: "100g",
    dimensions: { length: "30cm", width: "21cm", height: "0.5cm" },
    material: "Paper",
    colors: ["White"],
    size: ["A4", "A5"],
    reviews: [
      {
        reviewer: "Alice Johnson",
        rating: 4.5,
        comment: "Excellent quality paper, perfect for planners.",
      },
    ],
    salePrice: "600",
    relatedProducts: [4, 5],
    SKU: "FCS-PPR-003",
    dateAdded: "2024-03-01",
    manufacturer: "Focus Co.",
    warranty: "6 months",
    shippingDetails: "Free shipping on orders over ₹300",
    returnPolicy: "30-day return policy",
  },
  {
    id: 4,
    name: "Machined Pencil",
    href: "#",
    price: "₹450",
    description: "A precision-engineered mechanical pencil for professionals.",
    rating: 4.8,
    features: ["Durable", "Ergonomic", "Refillable"],
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-04.jpg",
    imageAlt:
      "Hand holding black machined steel mechanical pencil with brass tip and top.",
    isTrending: false,
    category: [{ name: "kids" }, { name: "stationery" }, { name: "trending" }],
    stock: 75,
    brand: "Machined",
    weight: "50g",
    dimensions: { length: "15cm", width: "0.8cm", height: "0.8cm" },
    material: "Steel",
    colors: ["Black"],
    size: ["Standard"],
    reviews: [
      {
        reviewer: "Michael Brown",
        rating: 4.8,
        comment: "Best mechanical pencil I've ever used.",
      },
    ],
    salePrice: "550",
    relatedProducts: [3, 6],
    SKU: "MCH-PCL-004",
    dateAdded: "2024-04-05",
    manufacturer: "Machined Co.",
    warranty: "1 year",
    shippingDetails: "Free shipping on orders over ₹500",
    returnPolicy: "30-day return policy",
  },
  {
    id: 5,
    name: "Travel Soap Container Box",
    href: "#",
    price: "₹49",
    description: "Soap container box for travel purpose.",
    rating: 4.5,
    features: ["Eco-friendly", "Durable"],
    imageSrc:
      "https://m.media-amazon.com/images/I/519mTmvllML._AC_UF1000,1000_QL80_.jpg",
    imageAlt: "Soap container box",
    isTrending: true,
    category: [{ name: "household" }],
    stock: 500,
    brand: "Travel Essentials",
    weight: "30g",
    dimensions: { length: "10cm", width: "7cm", height: "4cm" },
    material: "Plastic",
    colors: ["Blue", "Green"],
    size: ["Small", "Medium"],
    reviews: [
      {
        reviewer: "Laura Green",
        rating: 4.5,
        comment: "Very convenient for travel.",
      },
    ],
    salePrice: "84",
    relatedProducts: [1, 7],
    SKU: "TRV-SCP-005",
    dateAdded: "2024-05-10",
    manufacturer: "Travel Essentials Co.",
    warranty: "6 months",
    shippingDetails: "Free shipping on orders over ₹200",
    returnPolicy: "30-day return policy",
  },
  {
    id: 6,
    name: "Water Proof Mobile Cover Pouch",
    href: "#",
    price: "₹109",
    description: "Waterproof mobile cover pouch for your mobile phone.",
    rating: 4.0,
    features: ["Waterproof", "Durable"],
    imageSrc: "https://gadgetspro.in/wp-content/uploads/2022/08/yry.jpg",
    imageAlt: "Waterproof mobile cover pouch.",
    isTrending: true,
    category: [{ name: "household" }],
    stock: 300,
    brand: "GadgetsPro",
    weight: "20g",
    dimensions: { length: "18cm", width: "9cm", height: "1cm" },
    material: "Plastic",
    colors: ["Transparent"],
    size: ["Universal"],
    reviews: [
      {
        reviewer: "Daniel Lee",
        rating: 4.0,
        comment: "Works well, keeps my phone dry.",
      },
    ],
    salePrice: "149",
    relatedProducts: [5, 8],
    SKU: "GAD-WPC-006",
    dateAdded: "2024-06-15",
    manufacturer: "GadgetsPro Co.",
    warranty: "1 year",
    shippingDetails: "Free shipping on orders over ₹300",
    returnPolicy: "30-day return policy",
  },
  {
    id: 7,
    name: "Transparent Food Storage Container",
    href: "#",
    price: "₹149",
    description:
      "Transparent food storage container for organizing your kitchen.",
    rating: 4.5,
    features: ["Leak-proof", "Durable", "BPA-free"],
    imageSrc:
      "https://www.jiomart.com/images/product/original/rvzc5xas1s/home-pro-food-storage-container-transparent-container-capacity-300-ml-800ml-leak-proof-food-safe-freezer-safe-set-of-2-product-images-orvzc5xas1s-p602135042-0-202310011727.png?im=Resize=(420,420)",
    imageAlt: "Transparent food storage container.",
    isTrending: false,
    category: [{ name: "household" }],
    stock: 250,
    brand: "HomePro",
    weight: "100g",
    dimensions: { length: "12cm", width: "12cm", height: "6cm" },
    material: "Plastic",
    colors: ["Transparent"],
    size: ["300ml", "800ml"],
    reviews: [
      {
        reviewer: "Samantha White",
        rating: 4.5,
        comment: "Great for storing food, very sturdy.",
      },
    ],
    salePrice: "199",
    relatedProducts: [1, 6],
    SKU: "HMP-FSC-007",
    dateAdded: "2024-07-05",
    manufacturer: "HomePro Co.",
    warranty: "1 year",
    shippingDetails: "Free shipping on orders over ₹500",
    returnPolicy: "30-day return policy",
  },
  {
    id: 8,
    name: "Sticky Notes",
    href: "#",
    price: "₹29",
    description: "Colorful sticky notes for all your reminders and notes.",
    rating: 4.8,
    features: ["Bright colors", "Sticky", "Durable"],
    imageSrc:
      "https://5.imimg.com/data5/SELLER/Default/2024/5/417868016/JA/FK/NN/51081104/bja11402-2.jpg",
    imageAlt: "Colorful sticky notes.",
    isTrending: true,
    category: [{ name: "stationery" }],
    stock: 400,
    brand: "NoteMaster",
    weight: "10g",
    dimensions: { length: "7.6cm", width: "7.6cm", height: "0.5cm" },
    material: "Paper",
    colors: ["Yellow", "Pink", "Blue"],
    size: ["Small"],
    reviews: [
      {
        reviewer: "Chris Evans",
        rating: 4.8,
        comment: "Very useful for quick notes, love the colors.",
      },
    ],
    salePrice: "45",
    relatedProducts: [4, 7],
    SKU: "NTS-STK-008",
    dateAdded: "2024-07-15",
    manufacturer: "NoteMaster Co.",
    warranty: "6 months",
    shippingDetails: "Free shipping on orders over ₹200",
    returnPolicy: "30-day return policy",
  },
];

export const occasion = [
  {
    text: "BIRTHDAY",
    imageSrc:
      "https://plus.unsplash.com/premium_photo-1663839412026-51a44cfadfb8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8YmlydGhkYXl8ZW58MHx8MHx8fDA%3D",
    link: "/products?collection=Occasions&occasion=birthday",
  },
  {
    text: "ANNIVERSARY / WEDDING",
    imageSrc:
      "https://images.unsplash.com/photo-1512163143273-bde0e3cc7407?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8ZW5nYWdlbWVudCUyMHJpbmd8ZW58MHx8MHx8fDA%3D",
    link: "/products?collection=Occasions&occasion=anniversary-wedding",
  },
  {
    text: "HOUSEWARMING",
    imageSrc:
      "https://images.unsplash.com/photo-1619727875848-64f3b23a4de4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8aG91c2UlMjBnaWZ0fGVufDB8fDB8fHww",
    link: "/products?collection=Occasions&occasion=housewarming",
  },
];
